wip: cardview
SE2-Gwent/Gwent pull request #42
Opened 2022-04-07 16:55 UTC by mavalo99

2022-05-11 22:24 UTC, raphaelseher commented
|File|Coverage [4.39%]|:green_apple:|
|:-|:-:|:-:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/30f0e9899f194b95bd58de2224f70e499600770e/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|65.85%|:green_apple:|
|[Hero.java](https://github.com/SE2-Gwent/Gwent/blob/30f0e9899f194b95bd58de2224f70e499600770e/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FHero.java)|0%|:green_apple:|
|[PlayingCardDetailed.java](https://github.com/SE2-Gwent/Gwent/blob/30f0e9899f194b95bd58de2224f70e499600770e/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FPlayingCardDetailed.java)|0%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/30f0e9899f194b95bd58de2224f70e499600770e/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FStartFragment.java)|0%|:green_apple:|
|[MainActivity.java](https://github.com/SE2-Gwent/Gwent/blob/30f0e9899f194b95bd58de2224f70e499600770e/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FMainActivity.java)|0%|:green_apple:|
|[CardView.java](https://github.com/SE2-Gwent/Gwent/blob/30f0e9899f194b95bd58de2224f70e499600770e/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FCardView.java)|0%|:green_apple:|

|Total Project Coverage|23.76%|:green_apple:|
|:-|:-:|:-:|

2022-05-12 11:27 UTC, raphaelseher requested changes

2022-05-12 11:27 UTC, raphaelseher commented on app/src/main/res/layout/activity_main.xml
> +    android:id="@+id/Default_Background_Detailed"
Obsolete?

2022-05-12 11:27 UTC, raphaelseher commented on app/src/main/res/layout/activity_main.xml
> +    android:visibility="visible"
Obsolete?

2022-05-12 11:27 UTC, raphaelseher commented on app/src/main/java/at/aau/se2/gwent/PlayingCardDetailed.java
> +public class PlayingCardDetailed extends AppCompatActivity {
DetailCardView ist gemerged, diese Activity löschen und mit der von Kevin ersetzen, so wie hier aufrufen:
https://github.com/SE2-Gwent/Gwent/pull/46/files#diff-894fc26df703733daa3819363b76599837c45a936806b541016698daa485633bR97

2022-05-12 14:47 UTC, mavalo99 commented on app/src/main/java/at/aau/se2/gwent/PlayingCardDetailed.java
> +public class PlayingCardDetailed extends AppCompatActivity {
@raphaelseher 
Okay ich entferne die ganze Klasse. Soll auch die dazu gehörige XML raus?

2022-05-12 15:27 UTC, merged