WIP: BoardView
SE2-Gwent/Gwent pull request #60
Opened 2022-05-30 16:04 UTC by raphaelseher

2022-06-01 21:05 UTC, raphaelseher commented
|File|Coverage [39.56%]|:green_apple:|
|:-|:-:|:-:|
|[CardDecks.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FCardDecks.java)|93.22%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|88.07%|:green_apple:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|86.24%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|83.5%|:green_apple:|
|[BoardViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewModel.java)|0%|:green_apple:|
|[BoardViewData.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewData.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|
|[CardDetails.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FCardDetails.java)|0%|:green_apple:|
|[DetailedCardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FDetailedCardFragment.java)|0%|:green_apple:|
|[CardRowHelper.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FCardRowHelper.java)|0%|:green_apple:|
|[DebugHelper.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FDebugHelper.java)|0%|:green_apple:|
|[SingleEvent.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FSingleEvent.java)|0%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FStartFragment.java)|0%|:green_apple:|
|[GameDebugViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FGameDebugViewModel.java)|0%|:green_apple:|
|[MainActivity.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FMainActivity.java)|0%|:green_apple:|
|[CardView.java](https://github.com/SE2-Gwent/Gwent/blob/eaaa7f7533d532b7b1bab23d3e2bb217576c9441/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FCardView.java)|0%|:green_apple:|

|Total Project Coverage|29.21%|:green_apple:|
|:-|:-:|:-:|

2022-06-02 09:10 UTC, raphaelseher commented
|File|Coverage [39.54%]|:green_apple:|
|:-|:-:|:-:|
|[CardDecks.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FCardDecks.java)|93.22%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|88.07%|:green_apple:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|86.24%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|83.43%|:green_apple:|
|[BoardViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewModel.java)|0%|:green_apple:|
|[BoardViewData.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewData.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|
|[CardDetails.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FCardDetails.java)|0%|:green_apple:|
|[DetailedCardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FDetailedCardFragment.java)|0%|:green_apple:|
|[CardRowHelper.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FCardRowHelper.java)|0%|:green_apple:|
|[DebugHelper.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FDebugHelper.java)|0%|:green_apple:|
|[SingleEvent.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FSingleEvent.java)|0%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FStartFragment.java)|0%|:green_apple:|
|[GameDebugViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FGameDebugViewModel.java)|0%|:green_apple:|
|[MainActivity.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FMainActivity.java)|0%|:green_apple:|
|[CardView.java](https://github.com/SE2-Gwent/Gwent/blob/9bfef0c4bdce5424598d9f8938c38dc6fd2ef332/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FCardView.java)|0%|:green_apple:|

|Total Project Coverage|29.2%|:green_apple:|
|:-|:-:|:-:|

2022-06-02 09:44 UTC, raphaelseher commented
|File|Coverage [37.09%]|:green_apple:|
|:-|:-:|:-:|
|[CardDecks.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FCardDecks.java)|93.22%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|88.07%|:green_apple:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|86.24%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|83.43%|:green_apple:|
|[FirebaseConnector.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FFirebaseConnector.java)|1.48%|:green_apple:|
|[BoardViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewModel.java)|0%|:green_apple:|
|[BoardViewData.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewData.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|
|[CardDetails.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FCardDetails.java)|0%|:green_apple:|
|[DetailedCardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FDetailedCardFragment.java)|0%|:green_apple:|
|[CardRowHelper.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FCardRowHelper.java)|0%|:green_apple:|
|[DebugHelper.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FDebugHelper.java)|0%|:green_apple:|
|[SingleEvent.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FSingleEvent.java)|0%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FStartFragment.java)|0%|:green_apple:|
|[GameDebugViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FGameDebugViewModel.java)|0%|:green_apple:|
|[MainActivity.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FMainActivity.java)|0%|:green_apple:|
|[CardView.java](https://github.com/SE2-Gwent/Gwent/blob/d8c33f3be187c71c674ce239a8b0daf4eb0613ff/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FCardView.java)|0%|:green_apple:|

|Total Project Coverage|29.09%|:green_apple:|
|:-|:-:|:-:|

2022-06-02 11:43 UTC, raphaelseher commented
|File|Coverage [35.66%]|:green_apple:|
|:-|:-:|:-:|
|[CardDecks.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FCardDecks.java)|93.22%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|83.87%|:green_apple:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|83.67%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|47.71%|:green_apple:|
|[FirebaseConnector.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FFirebaseConnector.java)|1.53%|:green_apple:|
|[BoardViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewModel.java)|0%|:green_apple:|
|[BoardViewData.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewData.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|
|[CardDetails.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FCardDetails.java)|0%|:green_apple:|
|[DetailedCardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FDetailedCardFragment.java)|0%|:green_apple:|
|[CardRowHelper.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FCardRowHelper.java)|0%|:green_apple:|
|[DebugHelper.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FDebugHelper.java)|0%|:green_apple:|
|[SingleEvent.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FSingleEvent.java)|0%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FStartFragment.java)|0%|:green_apple:|
|[GameDebugViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FGameDebugViewModel.java)|0%|:green_apple:|
|[MainActivity.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2FMainActivity.java)|0%|:green_apple:|
|[CardView.java](https://github.com/SE2-Gwent/Gwent/blob/6fc31c726154a9129d43322e06f2094e45b0370d/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FCardView.java)|0%|:green_apple:|

|Total Project Coverage|28.18%|:green_apple:|
|:-|:-:|:-:|

2022-06-02 12:45 UTC, kuttnig approved these changes

2022-06-02 12:53 UTC, Sikredo requested changes

2022-06-02 12:53 UTC, Sikredo commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Lets exclude this file in the gitIgnore as it is in the .idea folder

2022-06-02 12:53 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/MainActivity.java
> +      case R.id.action_debug:
Should be placed on the StartFragment

2022-06-02 12:53 UTC, Sikredo commented on gamelogic/src/main/java/at/aau/se2/gamelogic/GameLogic.java
>        Log.w(TAG, "CardDecks not setup");
Should we do something in that case as there would be no cards?

2022-06-02 12:53 UTC, Sikredo commented on gamelogic/src/main/java/at/aau/se2/gamelogic/models/GameFieldRows.java
> +  private HashMap<String, Card> p1MeleeRow = new HashMap<>(10);
Lets use here a final const for the fixed value of 10

2022-06-02 12:53 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/board/BoardFragment.java
> +      cardView.setOnClickListener(
Lets move out the setOnClickListeners to a own private method as this is used here and in line 176-187

2022-06-02 12:53 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/board/BoardFragment.java
> +        cardView.setOnClickListener(
Same here, lets move this out to a method

2022-06-02 13:06 UTC, raphaelseher commented on app/src/main/java/at/aau/se2/gwent/views/board/BoardFragment.java
> +      cardView.setOnClickListener(
Sind zwei verschiedene methoden die gecallt werden. Da kriegen wir nit viel raus.
`didClickRowCard` und `didClickHandCard`

2022-06-02 13:54 UTC, raphaelseher commented
|File|Coverage [33.53%]|:green_apple:|
|:-|:-:|:-:|
|[CardDecks.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FCardDecks.java)|93.22%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|83.81%|:green_apple:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|83.67%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|47.71%|:green_apple:|
|[FirebaseConnector.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FFirebaseConnector.java)|1.53%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2FstartMenu%2FStartFragment.java)|0%|:green_apple:|
|[SettingsFragment.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fsettings%2FSettingsFragment.java)|0%|:green_apple:|
|[GameDebugViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdebug%2FGameDebugViewModel.java)|0%|:green_apple:|
|[GameDebugFragment.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdebug%2FGameDebugFragment.java)|0%|:green_apple:|
|[BoardViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewModel.java)|0%|:green_apple:|
|[BoardViewData.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewData.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|
|[CardDetails.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FCardDetails.java)|0%|:green_apple:|
|[DetailedCardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FDetailedCardFragment.java)|0%|:green_apple:|
|[CardRowHelper.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FCardRowHelper.java)|0%|:green_apple:|
|[DebugHelper.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Futil%2FDebugHelper.java)|0%|:green_apple:|
|[SingleEvent.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fcomunication%2FSingleEvent.java)|0%|:green_apple:|
|[CardView.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FCardView.java)|0%|:green_apple:|
|[RulesFragment.java](https://github.com/SE2-Gwent/Gwent/blob/71e73e2d424b6e42feb3541a6ff5dba89241b448/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Frules%2FRulesFragment.java)|0%|:green_apple:|

|Total Project Coverage|27.36%|:green_apple:|
|:-|:-:|:-:|

2022-06-02 14:11 UTC, merged