WIP: Sync CardActions via Firebase
SE2-Gwent/Gwent pull request #67
Opened 2022-06-07 16:29 UTC by kuttnig

2022-06-07 16:33 UTC, raphaelseher commented
|File|Coverage [79.85%]|:green_apple:|
|:-|:-:|:-:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/72bfcb6f3f87b9de0eea1c3a3c099f3849861e9f/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|79.85%|:green_apple:|

|Total Project Coverage|24%|:green_apple:|
|:-|:-:|:-:|

2022-06-13 22:10 UTC, raphaelseher commented
|File|Coverage [49.98%]|:green_apple:|
|:-|:-:|:-:|
|[RowStatus.java](https://github.com/SE2-Gwent/Gwent/blob/787664fc28a6d159af57cf19b833d089ee818adf/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRowStatus.java)|100%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/787664fc28a6d159af57cf19b833d089ee818adf/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|50.21%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/787664fc28a6d159af57cf19b833d089ee818adf/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|41.5%|:green_apple:|
|[Row.java](https://github.com/SE2-Gwent/Gwent/blob/787664fc28a6d159af57cf19b833d089ee818adf/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRow.java)|32.73%|:green_apple:|

|Total Project Coverage|22.79%|:green_apple:|
|:-|:-:|:-:|

2022-06-14 13:28 UTC, raphaelseher commented
|File|Coverage [48.78%]|:green_apple:|
|:-|:-:|:-:|
|[RowStatus.java](https://github.com/SE2-Gwent/Gwent/blob/ea4246e9e65de14b5871f880e4c2dc20798e4bcb/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRowStatus.java)|100%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/ea4246e9e65de14b5871f880e4c2dc20798e4bcb/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|48.87%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/ea4246e9e65de14b5871f880e4c2dc20798e4bcb/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|41.5%|:green_apple:|
|[Row.java](https://github.com/SE2-Gwent/Gwent/blob/ea4246e9e65de14b5871f880e4c2dc20798e4bcb/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRow.java)|32.73%|:green_apple:|

|Total Project Coverage|21.58%|:green_apple:|
|:-|:-:|:-:|

2022-06-14 13:47 UTC, raphaelseher commented
|File|Coverage [48.82%]|:green_apple:|
|:-|:-:|:-:|
|[RowStatus.java](https://github.com/SE2-Gwent/Gwent/blob/ea4ebad2da95ab8c469e4cb53a46eebc482b605d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRowStatus.java)|100%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/ea4ebad2da95ab8c469e4cb53a46eebc482b605d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|48.92%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/ea4ebad2da95ab8c469e4cb53a46eebc482b605d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|41.5%|:green_apple:|
|[Row.java](https://github.com/SE2-Gwent/Gwent/blob/ea4ebad2da95ab8c469e4cb53a46eebc482b605d/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRow.java)|32.73%|:green_apple:|

|Total Project Coverage|21.59%|:green_apple:|
|:-|:-:|:-:|

2022-06-16 21:17 UTC, raphaelseher requested changes

2022-06-17 20:28 UTC, kuttnig commented on gamelogic/src/main/java/at/aau/se2/gamelogic/models/GameFieldRows.java
> +  public Row getRangedRowFor(InitialPlayer player) {
Hab die Getter umgeschrieben. Sollte jetzt wieder funktionieren.

2022-06-19 14:36 UTC, raphaelseher commented
|File|Coverage [39.16%]|:green_apple:|
|:-|:-:|:-:|
|[RowStatus.java](https://github.com/SE2-Gwent/Gwent/blob/52dc057ee73a8c4047656e5a5069bc1d82450f6a/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRowStatus.java)|100%|:green_apple:|
|[GameLogic.java](https://github.com/SE2-Gwent/Gwent/blob/52dc057ee73a8c4047656e5a5069bc1d82450f6a/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2FGameLogic.java)|53.31%|:green_apple:|
|[GameFieldRows.java](https://github.com/SE2-Gwent/Gwent/blob/52dc057ee73a8c4047656e5a5069bc1d82450f6a/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameFieldRows.java)|48.43%|:green_apple:|
|[Row.java](https://github.com/SE2-Gwent/Gwent/blob/52dc057ee73a8c4047656e5a5069bc1d82450f6a/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FRow.java)|38.18%|:green_apple:|
|[BoardViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/52dc057ee73a8c4047656e5a5069bc1d82450f6a/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewModel.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/52dc057ee73a8c4047656e5a5069bc1d82450f6a/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|

|Total Project Coverage|22.81%|:green_apple:|
|:-|:-:|:-:|

2022-06-19 14:39 UTC, raphaelseher commented
Nächstes mal bitte Tests fixen vorm weitergeben. Sonst top!

2022-06-19 14:39 UTC, raphaelseher approved these changes

2022-06-19 14:39 UTC, raphaelseher commented on app/src/main/java/at/aau/se2/gwent/views/board/BoardFragment.java
> +      // playersHandCardViews.get(viewModel.getOldViewData().getSelectedCardId()).setSelected(false);
Wenn die Zeile einfach auskommentierst, weils crashed, dann kann man mehrere Karten auswählen beim ausspielen.

![image](https://user-images.githubusercontent.com/1867718/174485456-04be16b2-d2bf-4331-b442-549ec8f53af2.png)

2022-06-19 14:40 UTC, merged