PointView
SE2-Gwent/Gwent pull request #68
Opened 2022-06-09 15:11 UTC by raphaelseher

![Screenshot from 2022-06-09 17-09-02](https://user-images.githubusercontent.com/1867718/172881262-db2ac148-0f8a-44e3-affe-a7e3f7af83db.png)
![Screenshot from 2022-06-09 17-10-09](https://user-images.githubusercontent.com/1867718/172881270-6fc38d52-55ad-469e-a2f1-a99c493946d9.png)

2022-06-09 16:11 UTC, Sikredo requested changes

2022-06-09 16:11 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/common/PointView.java
> +    binding.turnTextView.setText(viewData.isMyTurn() ? "Your turn" : "Opponents turn");
Lets use a constant for "Your turn" and "Opponents turn"

2022-06-09 16:11 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/common/PointView.java
> +      binding.turnTextView.setText("Waiting for opponent");
Use also a constant string here

2022-06-09 16:11 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/common/PointView.java
> +    binding.turnTextView.setText(viewData.isMyTurn() ? "Your turn" : "Opponents turn");
Lets use a constant here for "Your turn" and "Opponents turn"

2022-06-09 16:11 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/common/PointView.java
> +      binding.turnTextView.setText("Waiting for opponent");
Also use a String constant here

2022-06-09 16:11 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/startMenu/StartFragment.java
> +        .setTitle("Join Game")
String constant

2022-06-09 16:11 UTC, Sikredo commented on app/src/main/java/at/aau/se2/gwent/views/startMenu/StartFragment.java
> +        .setMessage("Input GameId from other Player.")
String constant

2022-06-09 16:11 UTC, Sikredo commented on gamelogic/src/main/java/at/aau/se2/gamelogic/models/GameField.java
>      if (player == null) return 0;
Should we here return -1 as this is kind of an Error case?

2022-06-09 16:20 UTC, raphaelseher commented on gamelogic/src/main/java/at/aau/se2/gamelogic/models/GameField.java
>      if (player == null) return 0;
Default fürs UI ist eh 0 und im Fall des Falles, kann man auf dem Gamestate zurückgreifen und was anderes als 0 anzeigen.

2022-06-14 07:02 UTC, raphaelseher commented
|File|Coverage [11.08%]|:green_apple:|
|:-|:-:|:-:|
|[GameField.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/gamelogic%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgamelogic%2Fmodels%2FGameField.java)|82.89%|:green_apple:|
|[StartFragment.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2FstartMenu%2FStartFragment.java)|0%|:green_apple:|
|[GameDebugViewModel.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdebug%2FGameDebugViewModel.java)|0%|:green_apple:|
|[GameDebugFragment.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdebug%2FGameDebugFragment.java)|0%|:green_apple:|
|[BoardViewData.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardViewData.java)|0%|:green_apple:|
|[BoardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fboard%2FBoardFragment.java)|0%|:green_apple:|
|[DetailedCardFragment.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fdetailedcard%2FDetailedCardFragment.java)|0%|:green_apple:|
|[PointView.java](https://github.com/SE2-Gwent/Gwent/blob/a632059369377e372774cf504a5b7c2afe6652d0/app%2Fsrc%2Fmain%2Fjava%2Fat%2Faau%2Fse2%2Fgwent%2Fviews%2Fcommon%2FPointView.java)|0%|:green_apple:|

|Total Project Coverage|22.88%|:green_apple:|
|:-|:-:|:-:|

2022-06-14 07:05 UTC, merged